### ISSUE TITLE
您的注册功能貌似出了问题

### ISSUE THREAD

**Issue by jxx-sixhh** [cjtcjt999/Koala-running-applet#1]
您好，因为最近想要学习基于taro和node的项目，所以找到了您的项目，在实践时发现无法注册，所以请问是出了什么问题呢？

**Comment by cjtcjt999** [comment]
您好，不能注册是因为后端api接口是本地localhost:3000，需要你本地3000端口启动node服务，node项目在我仓库里也有；
不过我刚提交了代码，后端接口现修改成我实际服务器地址，你现在可以拉取最新代码正常使用项目了。
